### ISSUE TITLE
Wrong use of date format.

### ISSUE THREAD

**Issue by assaffa** [orensrauch/solveqa-expense-tracker#9]
https://github.com/orensrauch/solveqa-expense-tracker/blob/a899b95be0b5debc691ff7415ef908314aacf218/server/controllers/auth.controller.js#L27

https://stackoverflow.com/questions/13154552/javascript-set-cookie-with-expire-time

**Comment by orensrauch** [comment]
Thank you for raising this issue, I had implemented [this solution ](https://github.com/orensrauch/solveqa-expense-tracker/blob/9db24f445c728967d8c37af48a0831d7cf590069/server/controllers/auth.controller.js#L30)
